# Application
base.url=http://localhost:8080

# Browser
browser=chrome

# User Credentials
username=Administrator
password=admin

# Wait Configuration
implicit.wait=10
explicit.wait=20
page.load.timeout=30

# Execution
headless=false

report.path=reports/AutomationReport.html
report.title=ERPNext Test Report
report.name=ERPNext Automation Execution Report
report.theme=STANDARD
tester=John
environment=QA